### ISSUE TITLE
IOError: File /mnt/altanalyze_output/AltResults/AlternativeOutput/Hs_RNASeq_top_alt_junctions-PSI_EventAnnotation.txt does not exist

### ISSUE THREAD

**Issue by Emptyset110** [frankligy/SNAF#23]
```
/data/SNAF$ sudo docker run -v $PWD:/mnt -t frankligy123/altanalyze:0.7.0.1 identify bam 16
[sudo] password for rebuilding: 
Current folder is /mnt
Identify splicing junction, bam folder is /mnt/bam, using 16 cores
start to get junction bed
library lxml not supported. WikiPathways and LineageProfiler visualization will not work. Please install with pip install lxml.
4412416 392051 11.2180259228 seconds required to parse the BAM file
start to get exon bed
library lxml not supported. WikiPathways and LineageProfiler visualization will not work. Please install with pip install lxml.
295.916596174 seconds to assign reads for 267 entries from 1793858 reference entries
mkdir: cannot create directory ‘bed’: File exists
mkdir: cannot create directory ‘altanalyze_output’: File exists
mkdir: cannot create directory ‘altanalyze_output/ExpressionInput’: File exists
library lxml not supported. WikiPathways and LineageProfiler visualization will not work. Please install with pip install lxml.
Starting AltAnalyze version 2.1.4.4
Using the Config location: /usr/src/app/altanalyze/Config//report.log
/usr/src/app/altanalyze/Config//options.txt
Options.txt found in local Config =  True ...confirmed found

AltAnalyze depedency not met for: patsy
...Combat batch effects correction requires pandas and patsy
AltAnalyze depedency not met for: wx
...The AltAnalyze Results Viewer requires wx
AltAnalyze depedency not met for: fastcluster
...Faster hierarchical cluster not supported without fastcluster
AltAnalyze depedency not met for: lxml
...Wikipathways visualization not supported without lxml

WARNING!!!! Some dependencies are not currently met.
This may impact AltAnalyze's performance

Running commandline options

Arguments input: ['/usr/src/app/altanalyze/AltAnalyze.py', '--species', 'Hs', '--platform', 'RNASeq', '--version', 'EnsMart91', '--bedDir', '/mnt/bed', '--output', '/mnt/altanalyze_output', '--groupdir', '/mnt/altanalyze_output/ExpressionInput/groups.original.txt', '--compdir', '/mnt/altanalyze_output/ExpressionInput/comps.original.txt', '--expname', 'original', '--runGOElite', 'no'] 

Current database version: EnsMart91
/usr/src/app/altanalyze/AltAnalyze.py --species Hs --platform RNASeq --version EnsMart91 --bedDir /mnt/bed --output /mnt/altanalyze_output --groupdir /mnt/altanalyze_output/ExpressionInput/groups.original.txt --compdir /mnt/altanalyze_output/ExpressionInput/comps.original.txt --expname original --runGOElite no
Groups file already present in target location OR bad input path.
Comparison file already present in target location OR bad input path.
Groups file already present in target location OR bad input path.
Comparison file already present in target location OR bad input path.
Beginning AltAnalyze Analysis... Format: non-log
AltAnalyze version 2.1.4.4 - Expression Analysis Parameters Being Used...
	database: EnsMart91
	species: Hs
	method: RNASeq
	manufacturer: RNASeq
	probability_statistic: moderated t-test
	constitutive_source: Ensembl
	dabg_p: 1.0
	junction expression threshold: 5.0
	exon_exp_threshold: 5.0
	gene_exp_threshold: 200.0
	exon_rpkm_threshold: 0.5
	gene_rpkm_threshold: 1.0
	exclude low expressing exons for RPKM: no
	avg_all_for_ss: yes
	expression_data_format: non-log
	include_raw_data: no
	run_from_scratch: Process RNA-seq reads
	perform_alt_analysis: yes
	calculate_gene_expression_using: core
Alternative Exon Analysis Parameters Being Used...
	analysis_method: MultiPath-PSI
	p_threshold: 0.05
	filter_data_types: all
	alt_exon_fold_variable: 0.1
	gene_expression_cutoff: 10.0
	remove_intronic_junctions: no
	avg_all_for_ss: yes
	permute_p_threshold: 0.05
	perform_permutation_analysis: no
	export_NI_values: yes
	run_MiDAS: no
	use_direct_domain_alignments_only: inferred comparison
	microRNA_prediction_method: any
	analyze_all_conditions: pairwise
	filter_for_AS: no
	run_GOElite: decide_later
Running command line mode: yes
multiThreading: True
Writing AltDatabase/Hs/RNASeq/Hs_Ensembl_exons.txt
Processing exon/junction coordinates sequentially by chromosome
Note: this step is time intensive (can be hours) and no print statements may post for a while
Using 32 processes
finished parsing data for chromosome: chrMT
finished parsing data for chromosome: chr22
finished parsing data for chromosome: chr14
finished parsing data for chromosome: chr21
finished parsing data for chromosome: chrY
finished parsing data for chromosome: chr13
finished parsing data for chromosome: chr18
finished parsing data for chromosome: chr20
finished parsing data for chromosome: chr4
finished parsing data for chromosome: chr9
finished parsing data for chromosome: chrX
finished parsing data for chromosome: chr17
finished parsing data for chromosome: chr8
finished parsing data for chromosome: chr7
finished parsing data for chromosome: chr10
finished parsing data for chromosome: chr12
finished parsing data for chromosome: chr15
finished parsing data for chromosome: chr11
finished parsing data for chromosome: chr6
finished parsing data for chromosome: chr5
finished parsing data for chromosome: chr3
finished parsing data for chromosome: chr16
finished parsing data for chromosome: chr2
finished parsing data for chromosome: chr19
finished parsing data for chromosome: chr1
Read exon and junction mapping complete
...RNA-seq import completed in 20 seconds

RPKM normalization complete
Imported Junction Statistics:
     20360 junctions found in Ensembl/UCSC and 1224 are novel
     64 trans-splicing junctions found (two aligning Ensembl genes)
     175 junctions where neither splice-site aligned to a gene
User databases and read counts written to: /mnt/altanalyze_output/ExpressionInput
Beginning to process the Hs RNASeq dataset
21900 Ensembl GO/pathway annotations imported in 1 seconds
21900 Ensembl GO/pathway annotations imported in 1 seconds
64661 constitutive genes and 1228297 junction IDs imported out of 1228298 lines.
64661 constitutive genes and 1314350 junction IDs imported out of 86071 lines.
Exon data imported in 0 seconds
Reorganizing expression data into comparison groups for export to down-stream splicing analysis software
Traceback (most recent call last):
  File "/usr/src/app/altanalyze/ExpressionBuilder.py", line 1979, in remoteExpressionBuilder
    try: probeset_db,annotate_db,comparison_filename_list = ExonArray.getAnnotations(fl,array_type,dabg_p,expression_threshold,data_source,vendor,constitutive_source,species,avg_all_for_ss,filter_by_dabg,perform_alt_analysis,expression_data_format)
  File "/usr/src/app/altanalyze/build_scripts/ExonArray.py", line 650, in getAnnotations
    comparison_filename_list,biotypes = exportGroupedComparisonProbesetData(expr_input_dir,probeset_db,data_type,array_names,array_linker_db,perform_alt_analysis)
  File "/usr/src/app/altanalyze/build_scripts/ExonArray.py", line 217, in exportGroupedComparisonProbesetData
    group_count,raw_data_comp_headers = reorder_arrays.reorderArrayHeaders(array_names,expr_group_list,comp_group_list,array_linker_db)
  File "/usr/src/app/altanalyze/reorder_arrays.py", line 47, in reorderArrayHeaders
    g2_headers = data_headers2[group2]
KeyError: 2

Error ecountered for the Hs, RNASeq dataset. Check to ensure that:
(1) the correct platform and species were selected and
(2) some expression values are present in ExpressionInput/exp.YourDataset.txt
Error ecountered for the Hs, RNASeq dataset. Check to ensure that:
(1) the correct platform and species were selected and
(2) some expression values are present in ExpressionInput/exp.YourDataset.txt
prune the raw junction count matrix
Traceback (most recent call last):
  File "/usr/src/app/prune.py", line 14, in <module>
    ee = [':'.join(item.split('|')[0].split(':')[1:]) for item in pd.read_csv('/mnt/altanalyze_output/AltResults/AlternativeOutput/Hs_RNASeq_top_alt_junctions-PSI_EventAnnotation.txt',sep='\t')['UID']]
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File /mnt/altanalyze_output/AltResults/AlternativeOutput/Hs_RNASeq_top_alt_junctions-PSI_EventAnnotation.txt does not exist
```

**Comment by frankligy** [comment]
Hi @Emptyset110,

Sorry for the inconvenience you are experiencing on your end. From what I can see here, first, it is complaining that there are already `/bed` and `/altanalyze_output` folder in your current directory. Just to summarize some key points that have caused issues for previous users:

* make sure you are in a folder (cd to that folder), where you have all your bam file stored in a sub-folder (for instance, you name this folder as bam), and there should be NO sub-folders named bed or altanalyze_output 
* you run either the singularity or docker using the command I wrote in the tutorial, modify the folder of your bam accordingly, depending on how you name the folder, also modify the number of cores you want, in the tutorial I said 4 
* if you only have one bam file, make sure to make a copy to make two bam files,  because altanalyze was originally designed for cohort level analysis. 
* your bam file should be hg38 aligned. 
* make sure for your bam file, no double underscore (__) are present in the bam file name

Another information I would like to know to help you debug, is how your current folder structure look like, the way how it is supposed to progress, is once you started the program, you will soon see a bunch of `.bed` file in your `/bam` folder, after about an hour, you will see these `.bed` file been moved to a new folder named `/bed`, and later, you will see all the results in another new folder called `/altanalyze_output`.The very last step is to post-process the `PSI-Event-annotation` file, the program complains that It can not find this file because properly the file was not properly generated. So I would like to know which step might have gone wrong, that's why I was asking how your current folder structure looks like.

@nsalomonis, do you happen to have any additional insights on the specific issue thrown here for AltAnalyze?

Thank you,
Frank

**Comment by Emptyset110** [comment]
Thank you for your reply. I realize that this is an issue not relating to this SNAF project. You have offer me useful suggestion:
 - There is only one bam file in the folder, I have two fastq files, I guess I need to start from fastq data.

**Comment by frankligy** [comment]
> Thank you for your reply. I realize that this is an issue not relating to this SNAF project. You have offer me useful suggestion:
> 
> * There is only one bam file in the folder, I have two fastq files, I guess I need to start from fastq data.

I see, yeah the alignment steps need to be done prior to running AltAnalyze, we have recommended workflow (https://snaf.readthedocs.io/en/latest/troubleshooting.html#recommended-alignment-workflow) mainly for consistency with TCGA protocol, but other aligner-generated bam file should work as well. Hoping this can solve the problem, but if not, feel free to comment here, let's figure them out!

**Comment by Emptyset110** [comment]
@frankligy Hi, I'm still confused about the "two bam files" requirement. Even though I re-run the STAR align process with `--twopassMode Basic`, it only generate a single merged bam file.
```
~/git/STAR/source/STAR --runThreadN 16 \
     --genomeDir /data/datasets/hg38/gdc/GRCh38.d1.vd1/index/star \
     --readFilesIn /data/gufeng/RNA/FB23AF0167-F2D4J22GXF1-KE3FKEE1_R1.fastq /data/gufeng/RNA/FB23AF0167-F2D4J22GXF1-KE3FKEE1_R2.fastq \
     --outFileNamePrefix outputPrefix_ \
     --outSAMtype BAM SortedByCoordinate \
     --twopassMode Basic
```
Do simply make a copy of the bam file actually work?
