### ISSUE TITLE
Program freezes when processing large input files

### ISSUE THREAD

**Issue by LIH-WHU** [frankligy/SNAF#54]
Hello, Frank! My output stopped at this step and remained unchanged for about two days without any errors reported.

```
nohup: ignoring input
2024-11-23 14:30:03 starting initialization
Current loaded gtex cohort with shape (196365, 2629)
Adding cohort additional_healthy with shape (1951065, 89) to the database
now the shape of control db is (2030266, 2718)
2024-11-23 14:35:36 finishing initialization
reduce valid NeoJunction from 4033319 to 945284 because they are present in GTEx
```

I took the following steps to investigate the issue: I found that the process was in a sleeping (Sl) state, with no changes in I/O read/write or CPU usage.

<img width="775" alt="图片" src="https://github.com/user-attachments/assets/71a65c1a-8c6a-47db-834c-5a442984673f">
<img width="362" alt="图片" src="https://github.com/user-attachments/assets/5d47657b-0563-4dff-90e0-97e5a59fe177">
<img width="451" alt="图片" src="https://github.com/user-attachments/assets/159ef1fc-bb5c-4538-a9d8-960741fba661">
<img width="773" alt="图片" src="https://github.com/user-attachments/assets/af420194-20d9-42d9-aa43-ffd83f587be1">
<img width="517" alt="图片" src="https://github.com/user-attachments/assets/4aefda7a-4a91-4fb8-bdfa-2390bb6221e1">

I suspected it might be a network issue, so I made modifications following issue49. However, after about 12 hours at the same stage, the following error was reported:

```
nohup: ignoring input
2024-11-25 17:37:05 starting initialization
Current loaded gtex cohort with shape (196365, 2629)
Adding cohort additional_healthy with shape (1951065, 89) to the database
now the shape of control db is (2030266, 2718)
2024-11-25 17:42:13 finishing initialization
reduce valid NeoJunction from 4033319 to 945284 because they are present in GTEx
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/site-packages/snaf/snaf.py", line 1350, in subexon_tran
    attrs = dict_exonCoords[EnsID][subexon]  # [chr,strand,start,end,suffer]
KeyError: 'U1.1_8278'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/site-packages/snaf/snaf.py", line 1386, in subexon_tran
    attrs = dict_exonCoords[EnsID][subexon]
KeyError: 'U1.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/site-packages/snaf/snaf.py", line 379, in each_chunk_func
    nj.retrieve_junction_seq()
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/site-packages/snaf/snaf.py", line 1045, in retrieve_junction_seq
    seq2 = subexon_tran(subexon2,ensid,'site2',code)
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/site-packages/snaf/snaf.py", line 1389, in subexon_tran
    exon_seq = utrJunction(suffix,EnsID,strandUTR,chrUTR,flag)
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/site-packages/snaf/snaf.py", line 1298, in utrJunction
    exon_seq = retrieveSeqFromUCSCapi(chr_,int(site),int(otherSite))
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/site-packages/snaf/snaf.py", line 1312, in retrieveSeqFromUCSCapi
    dna = dict_fa[chr_][start-1:end]
KeyError: 'chrMT'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "03.ONT_SNAF_LOCAL.py", line 42, in <module>
    jcmq.run(hlas=hlas,outdir='/data/person/lab/lih/person/project/ovarian_cancer/OVTGS/09.SNAF/ONT/result')
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/site-packages/snaf/snaf.py", line 448, in run
    self.parallelize_run(kind=1,strict=strict)
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/site-packages/snaf/snaf.py", line 507, in parallelize_run
    result = collect.get()
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'chrMT'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/data/person/lab/lih/.conda/envs/SNAKE/lib/python3.7/site-packages/snaf/dash_app/app.py", line 20, in clear_assets
    imgs = os.listdir('assets')
FileNotFoundError: [Errno 2] No such file or directory: 'assets'
```

When I tested with a smaller input file (a subset of junctions from the original file), the process completed successfully regardless of whether I followed the modifications, although the results showed slight differences.

Output burden_stage3.txt when using original code

```
Batch4_sample2.bed	Batch5_sample2.bed	Batch2_sample2.bed	Batch6_sample3.bed	Batch4_sample3.bed	Batch1_sample1.bed	Batch5_sample3.bed	Batch3_sample1.bed	Batch5_sample1.bed	Batch4_sample1.bed	Batch6_sample2.bed	Batch2_sample1.bed	Batch3_sample2.bed	Batch1_sample2.bed	mean
ENSG00000000460:E32.1_169800970-I33.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.0	0.0	0.0	2.0	0.21428571428571427
ENSG00000000419:E1.4-I1.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.0	1.0	0.0	0.14285714285714285
ENSG00000023516:U0.1_42272083-E2.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000000457:E8.2-E9.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000023516:E2.1-E3.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000000460:E29.5-E32.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000000460:E32.1-E34.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000023516:E3.1-E4.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000000460:E24.4-E29.4	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
burden	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.0	1.0	1.0	2.0	0.3571428571428571
```

Output burden_stage3.txt when editing code as in issue49

```
Batch4_sample2.bed	Batch5_sample2.bed	Batch2_sample2.bed	Batch6_sample3.bed	Batch4_sample3.bed	Batch1_sample1.bed	Batch5_sample3.bed	Batch3_sample1.bed	Batch5_sample1.bed	Batch4_sample1.bed	Batch6_sample2.bed	Batch2_sample1.bed	Batch3_sample2.bed	Batch1_sample2.bed	mean
ENSG00000000460:E32.1_169800970-I33.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	2.0	2.0	0.2857142857142857
ENSG00000000419:E1.4-I1.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.0	1.0	0.0	0.0	0.14285714285714285
ENSG00000000457:E8.2-E9.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000023516:E2.1-E3.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000023516:E3.1-E4.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000000460:E24.4-E29.4	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000000460:E32.1-E34.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000023516:U0.1_42272083-E2.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
ENSG00000000460:E29.5-E32.1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
burden	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.0	1.0	2.0	2.0	0.42857142857142855
```

I would like to ask: how can I avoid this issue when processing large input junction files? 
Alternatively, can I split the larger input file into smaller parts based on junctions, process them separately, and then merge the results? Will this affect the accuracy of the final results?

Looking forward to your reply! Thank you very much!
Li Hao

**Comment by LIH-WHU** [comment]
Hi Frank! Thank you so much for your reply. Apologies for the delayed response.
We proceeded with ​​Issue 49​​ to achieve more stable results. By splitting the large file into smaller subsets, the process ran smoothly. Thank you for developing such an incredible tool!
